spring:
  application:
    name: CampsiteReservation

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
        enabled: true
  jpa:
    hibernate:
        hbm2ddl:
            auto: create    

    

